# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8mb4_bin
  reconnect: false
  database: insideout_dev
  pool: 5
  username: root
  password: MyNewPass
  host: localhost
  port: 3306
  collation: utf8mb4_bin

production:
  adapter: mysql2
  encoding: utf8mb4_bin
  url: <%= ENV['DATABASE_URL'] %>
  pool: 15
  collation: utf8mb4_bin
